name: CI-Calculadora-Profissional

on:
  push:
    branches: [ "main", "master", "dev", "testes", "infra-ci-cd" ]
  pull_request:
    branches: [ "main", "master", "dev" ]

jobs:
  build-and-qa:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Executar Testes Unitários (Jest)
        run: npm test

      - name: 🤖 Executando Cypress
        uses: cypress-io/github-action@v6
        with:
          # Sobe o site da pasta public na porta 3000
          start: npx serve public -p 3000
          wait-on: 'http://localhost:3000'
          # Dá tempo para o servidor estabilizar no GitHub
          wait-on-timeout: 60